name: github actions demo
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "triggered by ${{github.event_name}} event"
      - run: echo "running on ${{runner.os}}"
      - name: check out repo code
        uses: actions/checkout@v2
      - run: echo "the ${{github.repository}} has been cloned"
      - name: list files in the repo
        run: |
          ls ${{github.workspace}}
